export { htmlIcon } from "./htmlIcon";
export {cssIcon} from "./cssIcon"
export {javascriptIcon} from "./javascriptIcon"
export {reactIcon} from "./reactIcon"
export {nextIcon} from "./nextIcon"
export {taillwindIcon} from "./taillwindIcon"
export {bootstrapIcon} from "./bootstrapIcon"
export {sassIcon} from "./sassIcon"
export {reduxIcon} from "./reduxIcon"
export {gitIcon} from "./gitIcon"
export {responsiveIcon} from "./responsiveIcon"
export {rightIcon} from "./rightIcon"
export {leftIcon} from "./leftIcon"
export {typescriptIcon} from "./typescriptIcon"
export {nodejsIcon} from "./nodejsIcon"
export {vueIcon} from "./vueIcon"